name: oce_py
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7   # Python version 3.7 or newer
    - basemap       # mapping package
    - bottleneck    # C-optimized array functions for NumPy
    - cartopy       # Geographic plotting toolkit
    - cython        # Transpile Python->C
    - dask          # Parallel processing library
    - h5py          # Wrapper for HDF5
    - notebook      # Jupyter notebook classic ver.
    - jupyter       # Jupyter architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - pandas        # Labeled array library
    - proj4         # geographic projections
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - xarray        # N-d labeled array library
pip:
    - argopy        # Argo data access
    - gsw           # TEOS Gibbs Seawater properties
